package com.bless.ospm.model.base;

// Generated 2013-5-17 11:14:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RoleResourceRef generated by hbm2java
 */
@Entity
@Table(name = "disease_health_ref", catalog = "shpt")
public class DiseaseHealthRef implements java.io.Serializable {

	private String id;
	private DiseaseCode deseaseCode;
	private HealthIndicator healthIndicator;
	private Byte status;
	private Date createTime;
	private Date modifyTime;
	public DiseaseHealthRef() {
	}


	public DiseaseHealthRef(DiseaseCode deseaseCode, HealthIndicator healthIndicator) {
		super();
		this.deseaseCode = deseaseCode;
		this.healthIndicator = healthIndicator;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disease_id")
	public DiseaseCode getDeseaseCode() {
		return deseaseCode;
	}


	public void setDeseaseCode(DiseaseCode deseaseCode) {
		this.deseaseCode = deseaseCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "health_indicator_id")
	public HealthIndicator getHealthIndicator() {
		return healthIndicator;
	}


	public void setHealthIndicator(HealthIndicator healthIndicator) {
		this.healthIndicator = healthIndicator;
	}

	@Column(name = "status_dh")
	public Byte getStatus() {
		return status;
	}


	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "create_time")
	public Date getCreateTime() {
		return createTime;
	}


	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_time")
	public Date getModifyTime() {
		return modifyTime;
	}


	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}


	

	

}
