package com.bless.ospm.model.base;

// Generated 2013-5-24 10:46:36 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserOrgRef generated by hbm2java
 */
@Entity
@Table(name = "user_org_ref", catalog = "shpt")
public class UserOrgRef implements java.io.Serializable {

	private long id;
	private User user;
	private Organization organization;

	public UserOrgRef() {
	}

	public UserOrgRef(long id) {
		this.id = id;
	}

	public UserOrgRef(long id, User user, Organization organization) {
		this.id = id;
		this.user = user;
		this.organization = organization;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id")
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

}
