package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "car", catalog = "igov")
public class Car implements java.io.Serializable {

	private Long id;
	private String carNo;
	private String fuelCardNo;
	private String gpsNo;
	private Long orgId;
	private String desc;
	private Set<MendRecord> mendRecords = new HashSet<MendRecord>(0);
	private Set<FuelRecord> fuelRecords = new HashSet<FuelRecord>(0);

	public Car() {
	}

	public Car(String carNo, String fuelCardNo, String gpsNo, Long orgId,
			String desc, Set<MendRecord> mendRecords,
			Set<FuelRecord> fuelRecords) {
		this.carNo = carNo;
		this.fuelCardNo = fuelCardNo;
		this.gpsNo = gpsNo;
		this.orgId = orgId;
		this.desc = desc;
		this.mendRecords = mendRecords;
		this.fuelRecords = fuelRecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "car_no", length = 40)
	public String getCarNo() {
		return this.carNo;
	}

	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	@Column(name = "fuel_card_no", length = 40)
	public String getFuelCardNo() {
		return this.fuelCardNo;
	}

	public void setFuelCardNo(String fuelCardNo) {
		this.fuelCardNo = fuelCardNo;
	}

	@Column(name = "gps_no", length = 40)
	public String getGpsNo() {
		return this.gpsNo;
	}

	public void setGpsNo(String gpsNo) {
		this.gpsNo = gpsNo;
	}

	@Column(name = "org_id")
	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	@Column(name = "desc", length = 200)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<MendRecord> getMendRecords() {
		return this.mendRecords;
	}

	public void setMendRecords(Set<MendRecord> mendRecords) {
		this.mendRecords = mendRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<FuelRecord> getFuelRecords() {
		return this.fuelRecords;
	}

	public void setFuelRecords(Set<FuelRecord> fuelRecords) {
		this.fuelRecords = fuelRecords;
	}

}
