package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Crim generated by hbm2java
 */
@Entity
@Table(name = "crim", catalog = "igov")
public class Crim implements java.io.Serializable {

	private Long id;
	private String name;
	private Byte sex;
	private String unId;
	private String phone;
	private String motorId;
	private String address;
	private String tempAddress;
	private String condition;
	private Byte type;
	private String firmName;
	private String personInLaw;
	private String regAddress;
	private String openAddress;
	private String businessLicense;
	private String firmType;
	private String agent;
	private Set<Event> events = new HashSet<Event>(0);

	public Crim() {
	}

	public Crim(String name, Byte sex, String unId, String phone,
			String motorId, String address, String tempAddress,
			String condition, Byte type, String firmName, String personInLaw,
			String regAddress, String openAddress, String businessLicense,
			String firmType, String agent, Set<Event> events) {
		this.name = name;
		this.sex = sex;
		this.unId = unId;
		this.phone = phone;
		this.motorId = motorId;
		this.address = address;
		this.tempAddress = tempAddress;
		this.condition = condition;
		this.type = type;
		this.firmName = firmName;
		this.personInLaw = personInLaw;
		this.regAddress = regAddress;
		this.openAddress = openAddress;
		this.businessLicense = businessLicense;
		this.firmType = firmType;
		this.agent = agent;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	@Column(name = "un_id", length = 40)
	public String getUnId() {
		return this.unId;
	}

	public void setUnId(String unId) {
		this.unId = unId;
	}

	@Column(name = "phone", length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "motor_id", length = 40)
	public String getMotorId() {
		return this.motorId;
	}

	public void setMotorId(String motorId) {
		this.motorId = motorId;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "temp_address", length = 200)
	public String getTempAddress() {
		return this.tempAddress;
	}

	public void setTempAddress(String tempAddress) {
		this.tempAddress = tempAddress;
	}

	@Column(name = "`condition`", length = 20)
	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	@Column(name = "type")
	public Byte getType() {
		return this.type;
	}

	public void setType(Byte type) {
		this.type = type;
	}

	@Column(name = "firm_name", length = 80)
	public String getFirmName() {
		return this.firmName;
	}

	public void setFirmName(String firmName) {
		this.firmName = firmName;
	}

	@Column(name = "person_in_law", length = 20)
	public String getPersonInLaw() {
		return this.personInLaw;
	}

	public void setPersonInLaw(String personInLaw) {
		this.personInLaw = personInLaw;
	}

	@Column(name = "reg_address", length = 200)
	public String getRegAddress() {
		return this.regAddress;
	}

	public void setRegAddress(String regAddress) {
		this.regAddress = regAddress;
	}

	@Column(name = "open_address", length = 200)
	public String getOpenAddress() {
		return this.openAddress;
	}

	public void setOpenAddress(String openAddress) {
		this.openAddress = openAddress;
	}

	@Column(name = "business_license", length = 100)
	public String getBusinessLicense() {
		return this.businessLicense;
	}

	public void setBusinessLicense(String businessLicense) {
		this.businessLicense = businessLicense;
	}

	@Column(name = "firm_type", length = 20)
	public String getFirmType() {
		return this.firmType;
	}

	public void setFirmType(String firmType) {
		this.firmType = firmType;
	}

	@Column(name = "agent", length = 20)
	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crim")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
