package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "igov")
public class Event implements java.io.Serializable {

	private Long id;
	private Law law;
	private Crim crim;
	private Term term;
	private Organization organization;
	private String code;
	private String source;
	private Date createTime;
	private String reporter;
	private String description;
	private String operAddress;
	private String process;
	private String processMethod;
	private String methodIntro;
	private Date endTime;
	private String illegal;
	private String resule;

	public Event() {
	}

	public Event(Law law, Crim crim, Term term, Organization organization,
			String code, String source, Date createTime, String reporter,
			String description, String operAddress, String process,
			String processMethod, String methodIntro, Date endTime,
			String illegal, String resule) {
		this.law = law;
		this.crim = crim;
		this.term = term;
		this.organization = organization;
		this.code = code;
		this.source = source;
		this.createTime = createTime;
		this.reporter = reporter;
		this.description = description;
		this.operAddress = operAddress;
		this.process = process;
		this.processMethod = processMethod;
		this.methodIntro = methodIntro;
		this.endTime = endTime;
		this.illegal = illegal;
		this.resule = resule;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "law")
	public Law getLaw() {
		return this.law;
	}

	public void setLaw(Law law) {
		this.law = law;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "crim_id")
	public Crim getCrim() {
		return this.crim;
	}

	public void setCrim(Crim crim) {
		this.crim = crim;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "term")
	public Term getTerm() {
		return this.term;
	}

	public void setTerm(Term term) {
		this.term = term;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id")
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@Column(name = "code", length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "source", length = 40)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "reporter", length = 20)
	public String getReporter() {
		return this.reporter;
	}

	public void setReporter(String reporter) {
		this.reporter = reporter;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "oper_address", length = 200)
	public String getOperAddress() {
		return this.operAddress;
	}

	public void setOperAddress(String operAddress) {
		this.operAddress = operAddress;
	}

	@Column(name = "process", length = 20)
	public String getProcess() {
		return this.process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	@Column(name = "process_method", length = 20)
	public String getProcessMethod() {
		return this.processMethod;
	}

	public void setProcessMethod(String processMethod) {
		this.processMethod = processMethod;
	}

	@Column(name = "method_intro", length = 200)
	public String getMethodIntro() {
		return this.methodIntro;
	}

	public void setMethodIntro(String methodIntro) {
		this.methodIntro = methodIntro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "illegal", length = 200)
	public String getIllegal() {
		return this.illegal;
	}

	public void setIllegal(String illegal) {
		this.illegal = illegal;
	}

	@Column(name = "resule", length = 40)
	public String getResule() {
		return this.resule;
	}

	public void setResule(String resule) {
		this.resule = resule;
	}

}
