package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FuelRecord generated by hbm2java
 */
@Entity
@Table(name = "fuel_record", catalog = "igov")
public class FuelRecord implements java.io.Serializable {

	private Long id;
	private Car car;
	private String name;
	private String cardType;
	private String fuelCardNo;
	private String fuelCardInner;
	private Date createTime;
	private Float l;
	private Float cost;
	private String mileage;
	private Float cardValue;
	private String memo;

	public FuelRecord() {
	}

	public FuelRecord(Car car, String name, String cardType, String fuelCardNo,
			String fuelCardInner, Date createTime, Float l, Float cost,
			String mileage, Float cardValue, String memo) {
		this.car = car;
		this.name = name;
		this.cardType = cardType;
		this.fuelCardNo = fuelCardNo;
		this.fuelCardInner = fuelCardInner;
		this.createTime = createTime;
		this.l = l;
		this.cost = cost;
		this.mileage = mileage;
		this.cardValue = cardValue;
		this.memo = memo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id")
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "card_type", length = 20)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "fuel_card_no", length = 40)
	public String getFuelCardNo() {
		return this.fuelCardNo;
	}

	public void setFuelCardNo(String fuelCardNo) {
		this.fuelCardNo = fuelCardNo;
	}

	@Column(name = "fuel_card_inner", length = 40)
	public String getFuelCardInner() {
		return this.fuelCardInner;
	}

	public void setFuelCardInner(String fuelCardInner) {
		this.fuelCardInner = fuelCardInner;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "L", precision = 4)
	public Float getL() {
		return this.l;
	}

	public void setL(Float l) {
		this.l = l;
	}

	@Column(name = "cost", precision = 6)
	public Float getCost() {
		return this.cost;
	}

	public void setCost(Float cost) {
		this.cost = cost;
	}

	@Column(name = "mileage", length = 20)
	public String getMileage() {
		return this.mileage;
	}

	public void setMileage(String mileage) {
		this.mileage = mileage;
	}

	@Column(name = "card_value", precision = 6)
	public Float getCardValue() {
		return this.cardValue;
	}

	public void setCardValue(Float cardValue) {
		this.cardValue = cardValue;
	}

	@Column(name = "memo", length = 600)
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
