package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Law generated by hbm2java
 */
@Entity
@Table(name = "law", catalog = "igov")
public class Law implements java.io.Serializable {

	private Long id;
	private String name;
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Term> terms = new HashSet<Term>(0);

	public Law() {
	}

	public Law(String name, Set<Event> events, Set<Term> terms) {
		this.name = name;
		this.events = events;
		this.terms = terms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "law")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "law")
	public Set<Term> getTerms() {
		return this.terms;
	}

	public void setTerms(Set<Term> terms) {
		this.terms = terms;
	}

}
