package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MegaEyes generated by hbm2java
 */
@Entity
@Table(name = "mega_eyes", catalog = "igov")
public class MegaEyes implements java.io.Serializable {

	private Long id;
	private String name;
	private String address;
	private String description;
	private String x;
	private String y;

	public MegaEyes() {
	}

	public MegaEyes(String name, String address, String description, String x,
			String y) {
		this.name = name;
		this.address = address;
		this.description = description;
		this.x = x;
		this.y = y;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "x", length = 40)
	public String getX() {
		return this.x;
	}

	public void setX(String x) {
		this.x = x;
	}

	@Column(name = "y", length = 40)
	public String getY() {
		return this.y;
	}

	public void setY(String y) {
		this.y = y;
	}

}
