package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "igov")
public class Member implements java.io.Serializable {

	private Long id;
	private Organization organization;
	private String name;
	private String login;
	private String description;
	private Byte status;
	private Byte category;
	private String exeCode;
	private Date expireTime;
	private String breastPiece;
	private String grade;
	private String duties;
	private Byte sex;
	private String phone;
	private String tel;
	private byte[] unId;

	public Member() {
	}

	public Member(Organization organization, String name, String login,
			String description, Byte status, Byte category, String exeCode,
			Date expireTime, String breastPiece, String grade, String duties,
			Byte sex, String phone, String tel, byte[] unId) {
		this.organization = organization;
		this.name = name;
		this.login = login;
		this.description = description;
		this.status = status;
		this.category = category;
		this.exeCode = exeCode;
		this.expireTime = expireTime;
		this.breastPiece = breastPiece;
		this.grade = grade;
		this.duties = duties;
		this.sex = sex;
		this.phone = phone;
		this.tel = tel;
		this.unId = unId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id")
	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "login", length = 40)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "category")
	public Byte getCategory() {
		return this.category;
	}

	public void setCategory(Byte category) {
		this.category = category;
	}

	@Column(name = "exe_code", length = 40)
	public String getExeCode() {
		return this.exeCode;
	}

	public void setExeCode(String exeCode) {
		this.exeCode = exeCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expire_time", length = 10)
	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	@Column(name = "breast_piece", length = 40)
	public String getBreastPiece() {
		return this.breastPiece;
	}

	public void setBreastPiece(String breastPiece) {
		this.breastPiece = breastPiece;
	}

	@Column(name = "grade", length = 20)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "duties", length = 20)
	public String getDuties() {
		return this.duties;
	}

	public void setDuties(String duties) {
		this.duties = duties;
	}

	@Column(name = "sex")
	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "tel", length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "un_id")
	public byte[] getUnId() {
		return this.unId;
	}

	public void setUnId(byte[] unId) {
		this.unId = unId;
	}

}
