package test;

// Generated 2013-6-3 11:33:12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Term generated by hbm2java
 */
@Entity
@Table(name = "term", catalog = "igov")
public class Term implements java.io.Serializable {

	private Long id;
	private Law law;
	private String name;
	private Set<Event> events = new HashSet<Event>(0);

	public Term() {
	}

	public Term(Law law, String name, Set<Event> events) {
		this.law = law;
		this.name = name;
		this.events = events;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "law_id")
	public Law getLaw() {
		return this.law;
	}

	public void setLaw(Law law) {
		this.law = law;
	}

	@Column(name = "name", length = 800)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "term")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

}
